In [1]:
import numpy as np

##Scalar

In [109]:
#generates random integer exclusive of provided number
dnpintsc=np.random.randint(17)
print(dnpintsc)

6


In [116]:
#generates random integer exclusive of provided number
dnpintsc=np.random.randn()
print(dnpintsc)

0.5183479773275704


##One Dimensional Array(also called vector)

In [3]:
#Create One dimensional array
dnpvector1=np.array([1,2,3,4,5,6,7])
print(dnpvector1)

[1 2 3 4 5 6 7]


In [4]:
#Create array from list
list1=[1,2,4,7,8,9]
dnplistarr=np.array(list1)
dnplistarr

array([1, 2, 4, 7, 8, 9])

In [5]:
#Cnverting numpy array to list
dnplistarr.tolist()

[1, 2, 4, 7, 8, 9]

In [6]:
#appending a value
dnpvector1=np.append(dnpvector1,10)
dnpvector1

array([ 1,  2,  3,  4,  5,  6,  7, 10])

In [7]:
#Inserting a value
#Insert value at specified index
dnpvector1=np.insert(dnpvector1,1,100)
dnpvector1

array([  1, 100,   2,   3,   4,   5,   6,   7,  10])

In [8]:
#sorting
np.sort(dnpvector1)

array([  1,   2,   3,   4,   5,   6,   7,  10, 100])

In [9]:
#deleting value from mentioned index
dnpvector1=np.delete(dnpvector1,1)
dnpvector1

array([ 1,  2,  3,  4,  5,  6,  7, 10])

In [10]:
dnpvector2=np.array([101,102,103])
dnpvector2

array([101, 102, 103])

In [11]:
#Concatenating arrays
dnpvector3=np.concatenate((dnpvector1,dnpvector2), axis=0)
dnpvector3

array([  1,   2,   3,   4,   5,   6,   7,  10, 101, 102, 103])

In [12]:
#reshape
dnpvector3.reshape(-1)

array([  1,   2,   3,   4,   5,   6,   7,  10, 101, 102, 103])

In [13]:
#Find index of array value
np.where(dnpvector3==7)

(array([6], dtype=int32),)

In [14]:
#Generates random integer including first parameter but excluding second parameter
dnpintarr=np.random.randint(2,5,17)
print(dnpintarr)

[2 3 3 2 4 2 3 3 2 4 2 4 2 2 3 2 3]


In [15]:
#Produce Array with numbers from 1 to 10, interval of 2
dnp1=np.arange(1,10,2)

In [16]:
#one dimensional array
dnp1

array([1, 3, 5, 7, 9])

In [17]:
#Array of zeros
dnpzero=np.zeros(10)
print(dnpzero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
#Array of ones
dnpones=np.ones(10)
print(dnpones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
#evenly spaced numbers
dnplinespace=np.linspace(1,5,20)
print(dnplinespace)

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


In [20]:
#array of random numbers
dnprandomarray=np.random.randn(16)
print(dnprandomarray)

[-1.76865566  0.44877883  1.65279147  0.9642689   1.14989971 -0.44664962
 -1.29255905 -2.04026537  0.4573302   1.24653905  1.23037704  0.02799583
  1.49594113 -0.34639749 -1.41667387  1.31684675]


In [21]:
#Finding Max and Minimum value of Array
print(dnprandomarray.max())
print(dnprandomarray.min())

1.6527914692877606
-2.0402653731995333


In [22]:
#Finding index of Max and Minimum value of Array
print(dnprandomarray.argmax())
print(dnprandomarray.argmin())

2
7


In [23]:
#Finding shape of array
dnprandomarray.shape

(16,)

In [24]:
#Finding size of array
dnprandomarray.size

16

In [25]:
#Fetch value at an specific index
print(dnprandomarray[5])

-0.44664961986729446


In [26]:
#Fetch value between mentioned index intervals
#starts with first number in range to one number before the second number in range
print(dnprandomarray[1:5])

[0.44877883 1.65279147 0.9642689  1.14989971]


##Multi-dimensional Array (also called Matrix)

In [29]:
#Array to matrix conversion
dnprandommatrix=dnprandomarray.reshape(4,4)
print(dnprandommatrix)

[[-1.76865566  0.44877883  1.65279147  0.9642689 ]
 [ 1.14989971 -0.44664962 -1.29255905 -2.04026537]
 [ 0.4573302   1.24653905  1.23037704  0.02799583]
 [ 1.49594113 -0.34639749 -1.41667387  1.31684675]]


In [30]:
#matrix of zeros
dnpzerosmatrix=np.zeros((3,5))
print(dnpzerosmatrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
#matrix of 0 nd 1
dnpidentity=np.eye(7)
print(dnpidentity)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [32]:
#matrix of random numbers
dnprandom=np.random.rand(5,4)
print(dnprandom)

[[0.21067598 0.07644456 0.51538545 0.81564459]
 [0.66354799 0.75554928 0.74104759 0.29199204]
 [0.54019744 0.96360781 0.62939973 0.07646806]
 [0.29973016 0.76815988 0.3176048  0.1235475 ]
 [0.39714328 0.95994687 0.43036685 0.08273214]]


In [33]:
#Find shape
print(dnprandom.shape)

(5, 4)


In [34]:
#Array with characters and numbers
dnchararray=([['hello'],['how'],['are'],['your'],[5]])
print(dnchararray)

[['hello'], ['how'], ['are'], ['your'], [5]]


In [35]:
#Find datatype
print(dnprandom.dtype)

float64


In [36]:
#Find specific value in matrix
#matrix[row][column]
#Specific value at row 4th and column 2nd
print(dnprandom[4][2])
print(dnprandom[4,2])

0.4303668539112995
0.4303668539112995


In [37]:
#Find value in matrix
#All the values of row 4
print(dnprandom[4])

[0.39714328 0.95994687 0.43036685 0.08273214]


In [38]:
#Find value in matrix
#All the values of column 2
print(dnprandom[:,2])

[0.51538545 0.74104759 0.62939973 0.3176048  0.43036685]


In [39]:
#Find value in matrix
#specific subset of matrix
print(dnprandom[1:3,2:4])

[[0.74104759 0.29199204]
 [0.62939973 0.07646806]]


##Operations on Numpy Matrix

In [40]:
#Create a matrix and assign values
dnpintmat=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(dnpintmat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [41]:
#check values greater than a specific number
print(dnpintmat>7)

[[False False False]
 [False False False]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [42]:
#check values between specific numbers
print((dnpintmat>7)&(dnpintmat<14))

[[False False False]
 [False False False]
 [False  True  True]
 [ True  True  True]
 [ True False False]]


In [43]:
dnpintmat2=[(dnpintmat>7)&(dnpintmat<14)]
print(dnpintmat[dnpintmat2])

[ 8  9 10 11 12 13]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


In [44]:
#Change values in matrix
dnpintmat[3:4]=100
print(dnpintmat)

[[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [100 100 100]
 [ 13  14  15]]


In [45]:
print(dnpintmat+50)

[[ 51  52  53]
 [ 54  55  56]
 [ 57  58  59]
 [150 150 150]
 [ 63  64  65]]


##Mathematical Functions

In [46]:
print(np.sum(dnpintmat))

387


In [47]:
print(np.std(dnpintmat))

37.31880669760668


In [48]:
print(np.sqrt(dnpintmat))

[[ 1.          1.41421356  1.73205081]
 [ 2.          2.23606798  2.44948974]
 [ 2.64575131  2.82842712  3.        ]
 [10.         10.         10.        ]
 [ 3.60555128  3.74165739  3.87298335]]


In [49]:
print(np.log(dnpintmat))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]
 [4.60517019 4.60517019 4.60517019]
 [2.56494936 2.63905733 2.7080502 ]]


In [50]:
print(np.exp(dnpintmat))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]
 [2.68811714e+43 2.68811714e+43 2.68811714e+43]
 [4.42413392e+05 1.20260428e+06 3.26901737e+06]]


##Some fun

In [51]:
#Converting numpy array to csv
np.savetxt("dnpintmat.csv",dnpintmat,delimiter=';')